services:  
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bryzndb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-management-service:
    image: ums
    container_name: user-management-service
    environment:
      SERVER_PORT: 8086
      
      # Spring
      SPRING_CONFIG_LOCATION: file:/app/config/
      SPRING_PROFILES_ACTIVE: test
      
      # Postgres 
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bryzndb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

      # CUSTOM
      SESSION_MANAGER: session-manager
      SESSION_MANAGER_PORT: 8090
      NOTIFICATION_SERVICE: notification-service
      NOTIFICATION_SERVICE_PORT: 8083

    depends_on:
      postgres:
        condition: service_healthy
    volumes:
    - ./config/application.properties:/app/config/application.properties
    ports:
      - "8086:8086"

  session-manager:
    image: sm
    container_name: session-manager
    environment:
        SERVER_PORT: 8090
        SPRING_CONFIG_LOCATION: file:/app/config/
        SPRING_PROFILES_ACTIVE: dev
    volumes:
    - ./config/application.properties:/app/config/application.properties
    ports:
      - "8090:8090"

volumes:
  pgdata: